title: "Hugging Face KREW"
email: heuristicwave@gmail.com
timezone: Asia/Seoul
baseurl: 
permalink: "/:title/"
logo: 'assets/images/hfkr_logo.png'
favicon: 'assets/images/favicon.ico'
author: Admin
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  math_engine: katex
  input: GFM
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# # Enable displaying posts with future dates
future: true

# Authors
authors:
  admin:
    name: HFKR Team
    display_name: Admin
    avatar: 'assets/images/logo.png'
    email: wowthemesnet@gmail.com
    web: https://hugging-face-krew.github.io/
    description: "Hugging Face KREW Team"
  chaewon:
    name: Song Chaewon
    display_name: Chaewon 
    avatar: 'assets/images/author/chaewon.png'
    email: chaewon1019@ewhain.net 
    web: https://github.com/chhaewxn/
    description: "Hello! I'm Chaewon Song, a developer aspiring to become an Software engineer 🤗"
  minju:
    name: Jwa Minju
    display_name: minju 
    avatar: 'assets/images/author/minju.png'
    email: jminj6@gmail.com 
    web: https://github.com/Jwaminju/
    description: "Hello, I'm minju! 🤗"
  sohyun:
    name: Sim Sohyun
    display_name: sohyun 
    avatar: 'assets/images/author/sohyun.png'
    email: sohyun.sim27@gmail.com 
    web: https://github.com/sim-so/
    description: "Hello, I'm sohyun, a data analyst who explores the world of data with curiosity and passion. 🤗"
  jeong:
    name: Ahn Jeong
    display_name: jeong 
    avatar: 'assets/images/author/jeong.JPG'
    email: ahnjj.dev@gmail.com 
    web: https://github.com/ahnjj/
    description: "Hello, I'm jeong!🤗"
  hyojung:
    name: Lee Hyojung
    display_name: hyojung
    avatar: 'assets/images/author/hyojung.png'
    email: eehyyo@gmail.com
    web: https://github.com/eehyo
    description: "Hello, I’m Hyojung Lee! 🤗"
  hyeonseo:
    name: Yun Hyeonseo
    display_name: hyeonseo
    avatar: 'assets/images/author/hyeonseo.png'
    email: 0525yhs@gmail.com
    web: https://github.com/hyeonseo2
    description: "Hello, I’m Hyeonseo! 🤗"
  Jimin:
    name: An Jimin
    display_name: Jimin
    avatar: 'assets/images/author/Jimin.png'
    email: jimin.an.1120@gmail.com
    web: https://github.com/jiminAn
    description: "Hello, I’m Jimin! I’m a NLP researcher in 🇰🇷"
  woojun:
    name: Woojun Jung
    display_name: 정우준
    avatar: 'assets/images/author/woojun.png'
    email: jungnerd@gmail.com
    web: https://github.com/jungnerd
    description: "🤗"
  youngjun:
    name: Cho Youngjun
    display_name: Youngjun
    avatar: 'assets/images/author/youngjun.png'
    email: whdudwns7777@gmail.com
    web: https://github.com/choincnp
    description: "안녕하세요! genAI 및 Agent에 관심있는 조영준입니다!"
  harheem:
    name: Harheem Kim
    display_name: harheem
    avatar: 'assets/images/author/harheem.png'
    email: shhr.kre@gmail.com
    web: https://www.linkedin.com/in/harheemk
    description: "안녕하세요. Hugging Face KREW를 애정하는 AI Engineer 김하림입니다."
  KREW:
    name: Hugging Face KREW Translation Bot
    display_name: Hugging Face KREW Translation Bot
    avatar: 'assets/images/author/KREW.png'
    email: huggingface.krew@gmail.com
    web: https://www.linkedin.com/company/hugging-face-krew/
    description: "Hugging Face 공식 블로그의 한국어 번역을 전하는 KREW Translation Bot입니다. 🤗"


# Social
social:
  instagram: https://www.instagram.com/bootstrapstarter/
  facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: https://twitter.com/bstartercom

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
